#159987624 Add user signup feature
andela/thor-ah-frontend pull request #10
Opened 2018-10-09 22:45 UTC by ozezzy

#### What does this PR do?
Enable  user to signup

#### Description of Task to be completed?
- create user signup reducer
- create and render signup form
- post user details and display errors if any
- add tests for user signup

#### How should this be manually tested?
Run 'npm install'
Run 'npm run start'
view interface on the browser

#### What are the relevant pivotal tracker stories?
[#159987624](https://www.pivotaltracker.com/story/show/159987624)

2018-10-10 09:26 UTC, iamuchejude requested changes

2018-10-10 09:26 UTC, iamuchejude commented on src/actions/user.signup.js
> +// const API = 'http://localhost:3001'
Remove commented code on line 10

2018-10-10 09:26 UTC, iamuchejude commented on src/components/Header/AuthMenu.js
> +          <button type='button' className={signupStyle.transparentBtn} onClick={this.toggleModal}><li>Register </li></button>
You enclosed `<li>` tag in `<button>` element. I don't think it's right that way.
It's better you attach your event to `<Link>` or have your button enclosed in `<li>`

2018-10-10 09:26 UTC, iamuchejude commented on src/containers/Signup/SignUp.module.css
> +/* body,html{
No commented code

2018-10-10 09:26 UTC, iamuchejude commented on src/tests/components/SocialSignup.test.js
> +});
Add a newline to this file

2018-10-10 09:26 UTC, iamuchejude commented on src/tests/containers/SignUp.test.js
> +    // it('should fail if no credentials are provided', () => {
Remove commented code

2018-10-10 09:26 UTC, iamuchejude commented on src/tests/reducers/user.reducer.test.js
> +});
Add a new line to this file

2018-10-10 09:42 UTC, iamuchejude approved these changes

2018-10-10 09:56 UTC, CEOehis approved these changes
LGTM

2018-10-10 10:27 UTC, d-beloved approved these changes
LGTM

2018-10-11 01:15 UTC, andela-ksolomon commented on src/actions/signup.js
> +} from './action.types';
Let's have the all the action types store in a separate folder called `types`. Just the same way we the actions and reducers

2018-10-11 14:06 UTC, merged