#161152337 fix header error and add 404 page
andela/thor-ah-frontend pull request #14
Opened 2018-10-12 18:00 UTC by ozezzy

#### What does this PR do?
fix bugs with frontend and add 404 page

#### Description of Task to be completed?
- Fix Header to Display Different Menu for Logged in user and Non-logged in user
- Horizontally Align the Search, Login and Register button properly
- Add Dropdown to the Header, so when a user clicks the avatar it displays
- Implement a 404 page for unknown routes

#### How should this be manually tested?
Run 'npm install'
Run 'npm run start'
view interface on the browser

#### What are the relevant pivotal tracker stories?
[#161152337](https://www.pivotaltracker.com/story/show/161152337)

2018-10-13 15:08 UTC, emekafredy requested changes
Hi @ozezzy. 
After checking out your work, I believe you did a tremendous job. The 404 page looks good and the redirection is appropriate. 
On the menu bar for a logged in user;
The cursor should show a 'pointer' ({cursor: pointer}) when hovering on the avatar, so the users know they can click on it to get some options. The same style should be applied to the login and signup buttons.
The publish option should only be available for users with the role of 'author'. Currently, users can see the publish sign on their menu bar and in the drop-down options.
On line 45 of the Menu.js component, you used 'lassName' instead of 'className'

2018-10-15 09:50 UTC, lauragift21 requested changes

2018-10-15 09:50 UTC, lauragift21 commented on src/components/Header/Menu.js
> +    console.log(role)
You might want to remove this concole.log statement on line 34.

2018-10-15 10:25 UTC, lauragift21 approved these changes

2018-10-15 10:28 UTC, emmaadesile requested changes

2018-10-15 10:28 UTC, emmaadesile commented on src/AppRoutes.js
> +        {/* will alsways render when no other path is matched */}
alsways should be always

2018-10-15 10:28 UTC, emmaadesile commented on src/components/Header/header.module.scss
> +  //border-bottom: 2px outset #eef;
Please remove commented out code. line 10

2018-10-15 10:43 UTC, emmaadesile approved these changes

2018-10-15 10:43 UTC, emekafredy approved these changes
LGTM

2018-10-15 12:14 UTC, johnkingzy approved these changes
Nice one!

2018-10-15 12:14 UTC, merged