#159987647 bookmark article for later
andela/thor-ah-frontend pull request #21
Opened 2018-10-17 03:47 UTC by ozezzy

#### What does this PR do?
add user able to favorite article feature

#### Description of Task to be completed?
- add action, reducer and component for favorite article
- add favorite article button to view article page

#### How should this be manually tested?
Run 'npm install'
Run 'npm run start'
navigate to single article page on the browser and click on options

#### What are the relevant pivotal tracker stories?
[#159987647](https://www.pivotaltracker.com/story/show/159987647)

2018-10-17 09:40 UTC, lauragift21 approved these changes
LGTM

2018-10-17 10:06 UTC, iamuchejude approved these changes
Good work

2018-10-17 10:06 UTC, iamuchejude commented on src/actions/favorite.js
> +const fialure = (payload) => ({
Guess you missed the spelling of `failure` here

2018-10-17 10:06 UTC, iamuchejude commented on src/components/ArticleContent/ArticleContent.js
> +                  {`${(article.timeToRead)} min read`}
What if you have more than 1min, `min` needs to be plural, right?
I will suggest you work that out by checking if `article.timeToRead` is greater than 1 to return `min` or `mins`

2018-10-17 10:53 UTC, ozezzy commented on src/components/ArticleContent/ArticleContent.js
> +                  {`${(article.timeToRead)} min read`}
Thanks for the attention to details Jude. I do think this is the standard, However, you can just slack Gif. she worked on the Article content I believe. I only changed line 65 of this file, not sure why it is showing more changes than that.

2018-10-17 11:31 UTC, iamuchejude commented on src/components/ArticleContent/ArticleContent.js
> +                  {`${(article.timeToRead)} min read`}
Copied.

2018-10-18 17:08 UTC, andela-ksolomon commented on src/components/Favorite/Favorite.js
> +        const { setMsg, message } = this.props
why not `setMessage` instead of `setMsg`
```suggestion
        const { setMessage, message } = this.props
```

2018-10-18 17:09 UTC, johnkingzy requested changes
👍 Good job.

2018-10-18 17:47 UTC, johnkingzy approved these changes

2018-10-18 17:48 UTC, merged