#161124006: Implement ability to view related articles
andela/thor-ah-frontend pull request #23
Opened 2018-10-17 16:37 UTC by lauragift21

#### What does this PR do?
It implements the ability to view related articles

#### Description of Task to be completed?
- Add related article functionality
- Write tests for functionality

#### How should this be manually tested?
-clone the repository
- cd into the directory and `npm install` and then run `npm start` 
- Navigate to `localhost:3000/articles/staying-fit` to view a sample of how the feature is implemented

#### What are the relevant pivotal tracker stories?
[#161124006](https://www.pivotaltracker.com/story/show/161124006)

#### Screenshots (if appropriate)

![screen shot 2018-10-17 at 5 35 38 pm](https://user-images.githubusercontent.com/17781315/47101892-2d4d3600-d233-11e8-9fa1-57e6be1040c5.png)
![screen shot 2018-10-17 at 5 35 57 pm](https://user-images.githubusercontent.com/17781315/47101894-2d4d3600-d233-11e8-84d3-f1fa7f0d8aaa.png)

2018-10-17 22:56 UTC, CEOehis requested changes

2018-10-17 22:56 UTC, CEOehis commented on src/tests/actions/relatedArticle.test.js
> +  xit("dispatches FETCH_RELATED_ARTICLE_SUCCESS", () => {
This test is skipped.

2018-10-18 05:48 UTC, lauragift21 commented on src/tests/actions/relatedArticle.test.js
> +  xit("dispatches FETCH_RELATED_ARTICLE_SUCCESS", () => {
Thanks I missed that

2018-10-18 13:32 UTC, gonuoha approved these changes
LGTM

2018-10-18 17:09 UTC, CEOehis approved these changes
👍 	LGTM

2018-10-18 17:26 UTC, johnkingzy approved these changes
LGTM

2018-10-18 22:26 UTC, merged