#159987643 Add Search Functionality and Custom filtering based on parameters
andela/thor-ah-frontend pull request #34
Opened 2018-10-23 05:01 UTC by emmaadesile

#### What does this PR do?
Users should be able to search for articles using and filter their search using keywords, tags or authors

#### Description of Task to be completed?
- Users can search for articles using keywords
- Users can search for articles using tags
- Users can search for articles using authors name

#### How should this be manually tested?
- after cloning the branch
- run `npm install` to install dependencies
- run `npm run dev` to start the dev server
- login and navigate to `/search` url
- enter the search parameter and choose the filter
- if articles are found for the search, it returns the articles based on the filter, else it returns not found

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[159987643](https://www.pivotaltracker.com/story/show/159987643)

#### Screenshots (if appropriate)
<img width="1430" alt="screen shot 2018-10-23 at 6 00 33 am" src="https://user-images.githubusercontent.com/26192691/47336799-022a7280-d689-11e8-80bc-756f2c6e6581.png">

#### Questions:

2018-10-23 09:47 UTC, emekafredy requested changes
Nice work so far @emmaadesile . I was able to search for articles by their keywords and I got results. However:
- Getting articles by their tags don't work
- Getting articles by the author's username throws an error, and I think you should be able to get articles by not just the author's username, but also the first name and last name.
<img width="1440" alt="screen shot 2018-10-23 at 10 31 59 am" src="https://user-images.githubusercontent.com/29521319/47352310-8d1f6300-d6b1-11e8-935a-48754a2d71fc.png">
- Also, clicking on any of the filter options (Tags, Authors, and Keywords), does not provoke any action.
<img width="1372" alt="screen shot 2018-10-23 at 10 33 18 am" src="https://user-images.githubusercontent.com/29521319/47352390-b5a75d00-d6b1-11e8-8c9a-e9fc808ed8dd.png">

2018-10-23 10:03 UTC, emmaadesile commented
@emekafredy When a user filters by an author, it searches using the username, first name or last name. I'll fix the error in code now.

2018-10-24 12:12 UTC, emekafredy approved these changes
LGTM

2018-10-24 14:05 UTC, iamuchejude requested changes
Good work on your implementation of this feature so far.
I pull the branch and testing on my local machine. By doing that, I came up an idea on UX. 
To start with, your search input field placeholder at the moment is `Search here`. Really great but I will suggest you replace it with something that tells them to press the `enter` key on their keyboard after typing to search since the form does not contain a submit button or does not search while user types.
Aside that, I must say your UI is really great and your choice of how to go about implementing this feature is a good on.

NB: I have also dropped some feedback on your PR for you implement.

2018-10-24 14:05 UTC, iamuchejude commented on src/actions/articleSearch.js
> +const articleSearch = (filter, searchValue) => dispatch => {
Cool implementation but I think this can be better implemented in this way
```js
const articleSearch = (searchValue, filter = null || 'keyword') => dispatch => {
	// lines 24 - 26 should come in here
	// lines 27 - 30 are no longer necessary here
	// remaining part of the function
}
```
From the code above, the default value for filter is null, so if you call this function like this:
`articleSearch('Boy')`, It will run fine.
If you pass in filter like this `articleSearch('Boy', { authored: '...' })` your code will also run fine.

I have applied bitwise operator and default parameter features in the snippets above. These links should lead you to resources to help you understand then better:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

However, you have been doing great so far.

2018-10-24 14:05 UTC, iamuchejude commented on src/containers/SearchResults/SearchResults.js
> +    if (filter === "" || filter === undefined || filter === null) {
Try implementing this using the bitwise operation feature
```js
filter = filter || 'keyword'
```
I have already dropped resources on bitwise in one of my comments

2018-10-24 14:13 UTC, emmaadesile commented on src/actions/articleSearch.js
> +const articleSearch = (filter, searchValue) => dispatch => {
Thanks. I appreciate the feedback. I will implement it now.

2018-10-24 15:18 UTC, iamuchejude approved these changes

2018-10-25 13:07 UTC, johnkingzy approved these changes
LGTM

2018-10-25 13:07 UTC, merged