#159987640 implement view notifications feature
andela/thor-ah-frontend pull request #37
Opened 2018-10-25 15:27 UTC by ozezzy

#### What does this PR do?
Enable view Notifications

#### Description of Task to be completed?
- Implement notifications badge
- Implement notifications dropdown
- Implement pusher to send notifications on real time
- Delete notifications when viewed

#### How should this be manually tested?
- after cloning the branch
- run `npm install` to install dependencies
- run `npm run dev` to start the dev server
- login and follow an author
- make the author create an article
- click on notifications badge
- select the notifications you would like to view

#### What are the relevant pivotal tracker stories?
[#159987640](https://www.pivotaltracker.com/story/show/#159987640)

2018-10-26 12:19 UTC, iamuchejude submitted a review, later dismissed
Brilliant Job @ozezzy 
However, I left some comments for you. Please check.

2018-10-26 12:19 UTC, iamuchejude commented on src/actions/notification.js
> +}).catch();
You should dispatch an error here. The reasons why notification did not come should be displayed on the notification dropdown so the user is more aware of what's going on.

2018-10-26 12:19 UTC, iamuchejude commented on src/actions/notification.js
> +}).catch()
You can still catch the error here and return in case of future debugging

2018-10-26 12:19 UTC, iamuchejude commented on src/components/ArticleContent/ArticleContent.js
> +  reload: state.notification.reload
Can you please explain what this state `reload` does?

2018-10-26 12:19 UTC, iamuchejude commented on src/components/Notification/Notification.js
> +const pusher = new Pusher('4ae9ed5cdec2db4a53e6', {
You should save app ID in the `.env` file

2018-10-26 12:19 UTC, iamuchejude commented on src/reducers/notification.js
> +export default function reducer(state = initialState.notification, action) {
There should be a state to store error. So,`NOTIFICATION_ERROR` should update error

2018-10-26 12:19 UTC, iamuchejude commented on src/tests/components/Notification.test.js
> +});
Newline(blank) is missing

2018-10-26 12:19 UTC, iamuchejude commented on src/components/ArticleContent/ArticleContent.js
> +  reload: state.notification.reload
I am also seeing that reload is not defined anywhere in your initial state. 
Could you please explain what the value of the initial state of `reload` is and what's is expected to be stored in it?

2018-10-26 13:00 UTC, iamuchejude requested changes
Brilliant work.
However, I dropped some comments for you to look into.

2018-10-26 14:01 UTC, emmaadesile requested changes
Great work. Please check the few comments I left on your PR

2018-10-26 14:01 UTC, emmaadesile commented on src/components/Notification/Notification.module.css
> +     /* margin-top: 10px; */
Remove commented out code. `line 53`

2018-10-26 14:01 UTC, emmaadesile commented on src/components/Notification/Notification.module.css
> +}
Add a new line here

2018-10-26 17:56 UTC, emmaadesile approved these changes

2018-10-26 17:57 UTC, iamuchejude approved these changes
Nice work

2018-10-27 00:33 UTC, johnkingzy approved these changes
LGTM

2018-10-27 00:33 UTC, merged