#161419917 Bug fixes
andela/thor-ah-frontend pull request #38
Opened 2018-10-26 04:25 UTC by d-beloved

#### What does this PR do?

-- Add pagination component to the categories page and favorite article page
-- Display list of articles on the categories page
-- Fix the all articles view in accordance to feedback
-- Replace highlight and comment icon with a better icon

#### How should this be manually tested?

-- Clone the repo from the latest change.
-- Install node.js on your local machine.
-- Clone the backend repo from [here](https://github.com/andela/thor-ah)
-- update the `.env` file on the backend according to the ```.env-sample```
-- Run ```npm install```
-- Run npm run dev.
-- Visit the landing page to see the new display for all articles
-- Visit the one article page, highlight a text and see the new icon
-- Visit the category page and see articles paginated if more than 12 articles are returned
-- Visit the favorite article page and see articles paginated if more than 6 articles are returned

#### What are the relevant pivotal tracker stories?

-- [#161419917](https://www.pivotaltracker.com/story/show/161419917)

#### Screenshots (if appropriate)
<img width="177" alt="screen shot 2018-10-26 at 05 24 19" src="https://user-images.githubusercontent.com/26516851/47544550-78c0ad80-d8df-11e8-9ba2-43be3d72b6f0.png">

2018-10-26 09:13 UTC, emekafredy approved these changes
LGTM

2018-10-26 11:22 UTC, emmaadesile requested changes
You did a great job. Please check the feedback that I left and make the necessary changes

2018-10-26 11:22 UTC, emmaadesile commented on src/actions/favouriteArticles.js
> +      console.log(err)
Good job on the actions. Please remove `console.log` statement here.

2018-10-26 11:22 UTC, emmaadesile commented on src/components/Articles/Articles.js
> +export default connect(mapStateToProps, mapDispatchToProps)(Articles);
You should include PropTypes in your Component. PropTypes is essentially a reference to what props your component needs and what type(s) they should be.

2018-10-26 11:22 UTC, emmaadesile commented on src/components/FavoriteArticles/FavoriteArticles.js
> +        <div className={ stylo.content_pagination }>
Please change this to something more descriptive `{ stylo.content_pagination }`

2018-10-26 11:26 UTC, d-beloved commented on src/components/FavoriteArticles/FavoriteArticles.js
> +        <div className={ stylo.content_pagination }>
No, that is not a typo. Another style has been imported into the file, and that uses ```styles```, to avoid collision, I used ```stylo``` to pull in the styles used by the pagination function.

2018-10-26 11:34 UTC, d-beloved commented on src/components/FavoriteArticles/FavoriteArticles.js
> +        <div className={ stylo.content_pagination }>
I have changed it to ```paginationStyle``` to make it more descriptive

2018-10-26 11:50 UTC, d-beloved commented on src/components/Articles/Articles.js
> +export default connect(mapStateToProps, mapDispatchToProps)(Articles);
Done

2018-10-26 11:54 UTC, emmaadesile approved these changes

2018-10-27 00:43 UTC, johnkingzy approved these changes
LGTM

2018-10-27 00:43 UTC, merged