#159987650 Users should be able to report an article
andela/thor-ah-frontend pull request #39
Opened 2018-10-26 16:45 UTC by emmaadesile

#### What does this PR do?
- Implement a feature that enables users to be able to report an article

#### Description of Task to be completed?
- users can click on the report article reaction
 - users can select the reason for the report and submit

#### How should this be manually tested?
- clone the branch
- run `npm install` to install app dependencies
- login into the app
- view an article
- click on the article reaction button beside the article like/dislike icons
- click the report article reaction
- choose a reason for the report and click submit

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[159987650](https://www.pivotaltracker.com/story/show/159987650)

#### Screenshots (if appropriate)
<img width="508" alt="screen shot 2018-10-26 at 5 44 50 pm" src="https://user-images.githubusercontent.com/26192691/47580464-e0f6aa00-d946-11e8-8fdc-a0ca80c08c8a.png">

#### Questions:
N/A

2018-10-26 17:33 UTC, ozezzy commented on src/actions/reportArticle.js
> +      dispatch(reportArticleLoading(false));
line 41 and line 44 can be replaced with a single dispatch before the if statement on line 40.

2018-10-26 17:38 UTC, ozezzy commented on src/components/ArticleReaction/ArticleReaction.module.css
> +}
You may want to remove commented code on line 30, and add a new line at the end of this file

2018-10-26 17:41 UTC, ozezzy commented on src/components/ReportArticle/ReportArticle.module.scss
> +}
you may wan't to add a new line here

2018-10-26 17:49 UTC, gonuoha approved these changes

2018-10-26 18:25 UTC, lauragift21 commented on src/assets/icons/close.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 8.586L2.929 1.515 1.515 2.929 8.586 10l-7.071 7.071 1.414 1.414L10 11.414l7.071 7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-
You can add an extra line here.

2018-10-26 18:29 UTC, lauragift21 requested changes

2018-10-26 18:29 UTC, lauragift21 commented on src/components/ArticleContent/ArticleContent.js
> +          <FaComment />{" "}
On line 130. You can take the empty object.

2018-10-26 18:29 UTC, lauragift21 commented on src/components/ArticleContent/ArticleContent.module.scss
> +}
At line 100, You can add a new line there too.

2018-10-28 13:22 UTC, lauragift21 approved these changes

2018-10-29 14:54 UTC, johnkingzy approved these changes
LGTM

2018-10-29 14:55 UTC, merged