Ft landing page 160950209
andela/thor-ah-frontend pull request #7
Opened 2018-10-08 11:56 UTC by iamuchejude

#### What does this PR do?
Create a landing(homepage) page for the app 

#### Description of Task to be completed?
When a user visits the platform, they should be able to see the Landing page. For now, you can set up the page with dummy data as soon as the 'Create Articles' feature is completed, it will be updated to work with dynamic data  

#### How should this be manually tested?
* Clone the repository
* CD into `thor-ah-frontend`
* Run `npm install`
* Run `npm start`
* Navigate to the `index` page

#### What are the relevant pivotal tracker stories?
[#160950209](https://www.pivotaltracker.com/story/show/160950209)

### Screenshots (if appropriate)
![localhost_3000_ 1](https://user-images.githubusercontent.com/38435631/46607570-5e25c080-caf9-11e8-8b7e-03b8ec7c1587.png)
![localhost_3000_ 2](https://user-images.githubusercontent.com/38435631/46607571-5e25c080-caf9-11e8-9df7-e6c662c8459e.png)
![localhost_3000_ 3](https://user-images.githubusercontent.com/38435631/46607572-5e25c080-caf9-11e8-882d-a11fd16b18e1.png)
![localhost_3000_ 4](https://user-images.githubusercontent.com/38435631/46607573-5ebe5700-caf9-11e8-9e07-1fc86c3a4d80.png)
![localhost_3000_](https://user-images.githubusercontent.com/38435631/46607574-5ebe5700-caf9-11e8-8e27-e57db93119bf.png)

2018-10-08 14:32 UTC, lauragift21 commented on src/styles/App.css
> +  font-family: 'Nunito Sans', sans-serif;
The default font family for the application should be Lato. So you can update this.

2018-10-08 14:34 UTC, lauragift21 commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,700" rel="stylesheet">
Same thing here too. The default font family should be `font-family: Lato`, So you can update this too.

2018-10-08 14:38 UTC, lauragift21 requested changes
LGTM 👍. I added a few comments for you check and update.

2018-10-08 14:50 UTC, emekafredy requested changes
Good work! The Article Categories can be located in the mobile version, but not the Desktop version. Please correct this.

2018-10-09 07:40 UTC, andela-ksolomon commented on src/components/Articles/Articles.js
> +          body: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
Is there any reason why you are setting the state in componentWillMount? I will suggest you set this directly in the initial state i.e `this.state = { articles: [ ......... ] }`

2018-10-09 07:42 UTC, andela-ksolomon commented on src/components/Articles/Articles.js
> +            const details = {
I will suggest you add a condition to display a message if no articles is found

2018-10-09 07:50 UTC, andela-ksolomon commented on src/components/Category/Category.js
> +import styles from './category.module.scss';
the previous comment also applies. Please add some comment between these lines

2018-10-09 07:51 UTC, andela-ksolomon commented on src/components/Header/Header.js
> +import Category from '../Category/Category';
Previous comment also applies, please add comments between the imports

2018-10-09 07:51 UTC, andela-ksolomon commented on src/components/Header/Menu.js
> +  border: '1px solid #000',
I will suggest you move this style into a different file

2018-10-09 07:52 UTC, johnkingzy requested changes
Nice one. Good job so far

2018-10-09 09:42 UTC, lauragift21 approved these changes

2018-10-09 11:09 UTC, emekafredy approved these changes
Looks Good

2018-10-09 13:23 UTC, johnkingzy approved these changes

2018-10-09 13:24 UTC, merged